# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'HOSPITAL_MGMT_SYSTEM'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'HOSPITAL_MGMT_SYSTEM'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Model configurations
models:
  HOSPITAL_MGMT_SYSTEM:
    stg_hospital_mgmt_system:  # Matches your folder name
      +schema: stg            # Staging models go into the 'stg' schema
      +materialized: table    # Default materialization is 'table'
    int_hospital_mgmt_system:  # Matches your folder name
      +schema: int            # Integration models go into the 'int' schema
      +materialized: table    # Default materialization is 'table'
      +description: "This model materializes as incremental and uses surrogate_key for uniqueness."
# Seed configuration
seeds:
  HOSPITAL_MGMT_SYSTEM:
    +schema: raw_data
    change_delimeters:  # Subfolder name under seeds
      +schema: raw_delimeter
      patients:  # Seed file name (without extension)
        +delimiter: "|"
      appointments:  # Another file within change_delimeters
        +delimiter: "~"
      billing:  # Another file within change_delimeters
        +delimiter: "\t"
      hospitals:  # Another file within change_delimeters
        +delimiter: ";"
      insurance:  # Another file within change_delimeters
        +delimiter: "^"
      physicians:  # Another file within change_delimeters
        +delimiter: ":"

snapshots:
  HOSPITAL_MGMT_SYSTEM:
    +schema: snapshot  # Specify the schema for snapshots