{{ config(materialized='view') }}

select * from
SURROGATE_KEY,
P_PATIENT_ID,
INSURANCE_ID,
PRIMARY_PHYSICIAN_ID,
APPOINTMENT_ID,
PHYSICIAN_ID,
HOSPITAL_ID,
INSURANCE_CLAIM_ID,
concat(P_FIRST_NAME,' ',P_LAST_NAME) as patient_full_name,
P_DATE_OF_BIRTH,
P_GENDER,
P_ADDRESS,
P_PHONE_NUMBER,
P_EMAIL,
ADMISSION_DATE,
DISCHARGE_DATE,
APPOINTMENT_DATE,
APPOINTMENT_TIME,
REASON_FOR_VISIT,
DIAGNOSIS,
TREATMENT_PLAN,
STATUS,
BILLING_AMOUNT,
COPAY_AMOUNT,
from
{{ ref('int_patients_appointments') }}