{{ config(materialized='view') }}

select
SURROGATE_KEY,
P_PATIENT_ID,
INSURANCE_ID,
PRIMARY_PHYSICIAN_ID,
coalesce(APPOINTMENT_ID,'9999')as APPOINTMENT_ID,
coalesce(PHYSICIAN_ID,'9999')PHYSICIAN_ID,
coalesce(HOSPITAL_ID,'9999')HOSPITAL_ID,
coalesce(INSURANCE_CLAIM_ID,'9999')INSURANCE_CLAIM_ID,
concat(P_FIRST_NAME,' ',P_LAST_NAME) as patient_full_name,
P_DATE_OF_BIRTH,
P_GENDER,
P_ADDRESS,
P_PHONE_NUMBER,
P_EMAIL,
ADMISSION_DATE,
DISCHARGE_DATE,
APPOINTMENT_DATE,
APPOINTMENT_TIME,
REASON_FOR_VISIT,
DIAGNOSIS,
TREATMENT_PLAN,
STATUS,
BILLING_AMOUNT,
COPAY_AMOUNT,
from
{{ ref('int_patients_appointments') }}